# Generated by Django 4.2.30 on 2026-07-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_customfielddefinition_customfieldoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presence_manual_status',
            field=models.CharField(choices=[('available', 'Available'), ('dnd', 'Do Not Disturb')], default='available', max_length=20),
        ),
    ]
