# Generated by Django 4.2.30 on 2026-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_alter_user_presence_manual_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='can_view_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
