# Generated by Django 4.2.30 on 2026-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_issuecommentvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushsubscription',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
