# Generated by Django 4.2.30 on 2026-07-20 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_workspacemember_team_and_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bd_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='db.workspacemember')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('profile_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bd_assignments', to='db.customfieldoption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Profile Assignment',
                'verbose_name_plural': 'Profile Assignments',
                'db_table': 'bd_profile_assignments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='profileassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'bd_member', 'profile_option'), name='uniq_project_bd_member_profile_option_when_not_deleted'),
        ),
    ]
