# Generated by Django 4.2.30 on 2026-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_bd_profile_assignment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['field', 'value_option'], name='cfv_field_option_active_idx'),
        ),
    ]
